allowBuilds:
  '@parcel/watcher': true
  cwebp-bin: false
  es5-ext: false
  gifsicle: false
  guetzli: false
  husky: false
  jpeg-recompress-bin: false
  mozjpeg: false
  optipng-bin: false
  pngquant-bin: false
  swiper: false
  zopflipng-bin: false
